name: ci

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                ports:
                    - 5432:5432
                env:
                    POSTGRES_PASSWORD: secret
                    POSTGRES_DB: bank_project
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: ^1.23

            - name: Set up environment variables
              run: cp .env.dev .env

            - name: Run migrations
              run: make migrationup

            - name: Test
              run: make test
